### PR TITLE
add descriptions and the instruction for asking a PR

### PR DESCRIPTION
**Pull request by yfhuang7**
Hey I review your repo, and I think it will be great if there is more description in the README file. :)

### CODE REVIEW

**Review by VerySpeedyPhoton — CHANGES_REQUESTED** [review]
This is great, but it's too many steps! can we combine steps 1 and 2?

**Comment by yfhuang7** [comment]
Yes, sure you can

**Review by VerySpeedyPhoton — APPROVED** [review]
Great, thank you for making the adjustment!

**Comment by VerySpeedyPhoton** [comment]
About to merge! Here we go...

**Pull request merged**
